global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'ink-playground'
    scrape_interval: 15s
    static_configs:
      - targets: ['playground:3000']
