[package]
name = "crate-extractor"
version = "0.1.0"
edition = "2018"
authors = ["Achim Schneider <achim@parity.io>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]

clap = "2.33.3"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = { version = "1.0.48", features = ["preserve_order"] }

crossbeam-channel = "0.5.0"
anyhow = "1.0.43"
log = "0.4.14"
tracing = "0.1"

change_json = {path="../change_json"}

ide_db = {package = "ra_ap_ide_db", version = "0.0.72"}
ide = {package = "ra_ap_ide", version = "0.0.72"}
hir = {package = "ra_ap_hir", version = "0.0.72"}
project_model = {package = "ra_ap_project_model", version = "0.0.72"}
vfs = {package = "ra_ap_vfs", version = "0.0.72"}
tt = {package = "ra_ap_tt", version = "0.0.72"}
vfs_notify = {package = "ra_ap_vfs-notify", version = "0.0.72"}
profile = {package = "ra_ap_profile", version = "0.0.72"}