[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Achim Schneider <achim@parity.io>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
actix-web = "4.1.0"
actix-web-prom = "0.6.0"
actix-files = "0.6.1"
clap = "4.0.22"
serde_json = "1.0.82"
serde = "1.0.143"
actix-cors = "0.6.1"
ts-rs = { git = "https://github.com/Aleph-Alpha/ts-rs", branch = "main", features = [
    "serde-compat",
] }
futures = "0.3.21"
hubcaps = "0.6.2"
tokio-compat-02 = "0.2.0"

sandbox = { path = "../sandbox" }

[dev-dependencies]
actix-rt = "2.7.0"

