[package]
name = "backend"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
readme = "README.md"


[dependencies]
actix-web = "3.3.2"
actix-rt = "2.2.0"
actix-files = "0.5.0"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }