apiVersion: v1
kind: Pod
metadata:
  name: ink-playground-pod
  namespace: default
  labels:
    app: ink-playground-app
spec:
  restartPolicy: Never
  serviceAccountName: ink-playground-service-account
  containers:
    - name: ink-playground-container
      image: ink-playground-kubernetes:latest
      imagePullPolicy: Never
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ACTIX_HOST
          value: '$ACTIX_HOST'
        - name: ACTIX_PORT
          value: '$ACTIX_PORT'
