apiVersion: v1
kind: Service
metadata:
  name: ink-playground-service
  namespace: ink-playground-namespace
spec:
  type: NodePort
  selector:
    app: ink-playground-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
