name: Compiler_Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Compare Cargo.toml files
        run: diff ./compiler/Cargo.toml ./crates/contract/Cargo.toml

      - name: Build docker
        run: docker build --tag ink-backend ./compiler/.

      - name: Login to DockerHub
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Tag Docker image
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        run: docker tag ink-backend:latest ${{ secrets.DOCKER_USER_NAME }}/ink-backend

      - name: Push Docker image
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/ink-backend
