name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Cache docker images
        uses: actions/cache@v2
        env:
          cache-name: cache-docker-images
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: get Sysbox
        run: wget https://downloads.nestybox.com/sysbox/releases/v0.4.1/sysbox-ce_0.4.1-0.ubuntu-focal_amd64.deb

      - name: Install Sysbox
        run: sudo apt-get install ./sysbox-ce_0.4.1-0.ubuntu-focal_amd64.deb

      - name: Configure Sysbox runtime
        run: sudo cp sysbox/daemon.json /etc/docker/daemon.json

      - name: Restart docker service
        run: sudo systemctl restart docker.service

      - name: Build docker
        run: make docker-build

      - name: Run docker
        run: make docker-run-detach
        env:
          DOCKER_PORT: 4000

      - name: Sleep for 120, allow Docker image to boot up
        uses: juliangruber/sleep-action@v1
        with:
          time: 120s

      - name: Install docker-tests
        run: yarn workspace docker-tests install

      - name: Test docker
        run: make docker-test
        env:
          DOCKER_PORT: 4000

      - name: docker log
        if: always()
        run: make docker-log
  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.repository == 'paritytech/ink-playground'
    steps:
      - name: Cache docker images
        uses: actions/cache@v2
        env:
          cache-name: cache-docker-images
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: docker tag ink-playground:latest ${{ secrets.DOCKER_USER_NAME }}/ink-playground

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/ink-playground

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}/redeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
