name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Pull `ink-backend` docker image
        run: docker pull docker.io/achimcc/ink-backend:latest

      - name: Tag `ink-backend` docker image
        run: docker tag docker.io/achimcc/ink-backend:latest ink-backend

      - name: Build docker
        run: make docker-build

      - name: Run docker
        run: make docker-run-detach
        env:
          PORT: 4000

      - name: Install docker-tests
        run: yarn workspace docker-tests install

      - name: Test docker
        run: make docker-test
        env:
          PORT: 4000

      - name: docker log
        if: always()
        run: make docker-log

      - name: Login to DockerHub
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Tag Docker image
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        run: docker tag ink-playground:latest ${{ secrets.DOCKER_USER_NAME }}/ink-playground

      - name: Push Docker image
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/ink-playground

      - name: Invoke deployment hook
        if: ${{ github.repository == 'paritytech/ink-playground' && github.ref == 'refs/heads/main' }}
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
