name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Pull `ink-backend` docker image
        run: docker pull docker.io/achimcc/ink-backend:latest

      - name: Tag `ink-backend` docker image
        run: docker tag docker.io/achimcc/ink-backend:latest ink-backend

      - name: Build docker
        run: make docker-build

      - name: Run docker
        run: make docker-run-detach
        env:
          PORT: 4000

      - name: Install docker-tests
        run: yarn workspace docker-tests install

      - name: Test docker
        run: make docker-test
        env:
          PORT: 4000

      - name: docker log
        if: always()
        run: make docker-log

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: docker tag ink-playground:latest achimcc/ink-playground

      - name: Push Docker image
        run: docker push achimcc/ink-playground
