name: Makefile

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  makefile:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - uses: actions/checkout@v3

      - name: Install
        run: make install

      - name: Install required rust toolchain
        run: rustup toolchain install nightly-2022-05-24

      - name: Add rust-src to toolchain
        run: rustup component add rust-src --toolchain nightly-2022-05-24-x86_64-unknown-linux-gnu

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Check `make generate` command
        run: make generate

      - name: Check `make build` command
        run: make build

      - name: Check `make backend-run` command
        run: nohup make backend-run &

      - name: Sleep for 10s, allow backend service to start
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s

      - name: Check if backend is up and running
        run: curl http://makefile:4000
