name: TypeScript

on: [push, pull_request]

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: TS install
        run: make ts-install

      - name: TS lint
        run: make ts-lint

  check-format:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: TS install
        run: make ts-install

      - name: TS check-format
        run: make ts-check-format

  check-spelling:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: TS install
        run: make ts-install

      - name: TS check-spelling
        run: make ts-check-spelling

  test-playground:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: TS install
        run: make ts-install

      - name: Generate
        run: make generate

      - name: Playground Test
        run: make playground-test

  test-components:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: TS install
        run: make ts-install

      - name: Components Test
        run: make components-test
