on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Install required nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-05-24-x86_64-unknown-linux-gnu
          override: true
          components: rust-src
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Run wasm-pack tests
        run: wasm-pack test --headless --chrome crates/rust_analyzer_wasm
        env:
          WASM_BINDGEN_TEST_TIMEOUT: 120
