on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Install required nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-11-04
          override: true
          components: rust-src
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Run wasm-pack test
        run: wasm-pack test --headless --chrome crates/rust_analyzer_wasm
        env:
          CC: /usr/local/opt/llvm/bin/clang
          AR: /usr/local/opt/llvm/bin/llvm-ar
