on: [push, pull_request]

jobs:
  test:
    if: ${{ false }}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-29-x86_64-unknown-linux-gnu
          override: true
          components: rust-src
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - run: wasm-pack test --headless --chrome crates/rust_analyzer_wasm
      - run: wasm-pack test --headless --firefox crates/rust_analyzer_wasm
